version: "3"

services:
  mlflow-server:
    build: .
    container_name: mlflow
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ~/.aws:/root/.aws
    entrypoint:
      /app/entrypoint.sh
    depends_on:
      - postgres

  postgres:
    image: postgres:11.1
    container_name: mlflow_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - mlflow-postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

volumes:
  mlflow-postgres-data: